### ISSUE TITLE
Warn when attempting to flush cache with `--url` on multisite

### ISSUE THREAD

**Issue by MannyAdumbire** [wp-cli/cache-command#78]
## Feature Request

- [ x ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

If I'm understanding right the `--url` flag is ignored when doing a `wp cache flush`. but no notice is given saying the flag is being ignored.

Is it feasible to update cache-command to clear caches for only subsite
 e.g. when below command is run
`wp cache flush --url=www.multisite.com/subsite`
only flush www.multisite.com/subsite but don't affect caches on www.multisite.com/ or www.multisite.com/other-subsite
 
 If not, maybe a notice that the flag is being ignored would be helpful.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @MannyAdumbire !

Your assessment is correct: `wp cache flush` affects the entire cache, not just a specific site.

> If not, maybe a notice that the flag is being ignored would be helpful.

This would be great! Want to submit a pull request for this? Here is some [guidance on our pull request best practices](https://make.wordpress.org/cli/handbook/contributions/pull-requests/), if it's helpful. You can also stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like to chat.

**Comment by WPprodigy** [comment]
I'm not sure that `Ignoring` is the right terminology here? WP CLI is still switching the context to subsite in question (as it should be). But the new warning label makes it seem otherwise, as if WP CLI isn't loading up the requested site.

Depending on the object cache implementation, it's possible that not all subsites have their cache flushed. For example: https://github.com/Automattic/wp-cache-memcached/blob/848365047f2edacec76e0b345809bb3f5ce5c2fb/includes/wp-object-cache.php#L630-L651

Could we maybe update this text a bit, perhaps something like:

> Warning: Flushing the cache may affect all sites in a multisite installation, depending on the object cache implementation.

Alternatively, a way to filter/remove this warning?

**Comment by danielbachhuber** [comment]
@WPprodigy I like your suggested changes to the text. Want to submit a PR?
